-- ============================================================================
-- CIMB Clicks Security Demonstration Prototype — Supabase (PostgreSQL) schema
-- Run this once in the Supabase SQL Editor (Dashboard > SQL Editor > New query).
-- The application seeds demo rows on startup; these statements only create tables.
-- ============================================================================

-- Module 1 — Authentication (CWE-20 / SR2)
create table if not exists users (
    username        text primary key,
    display_name    text        not null,
    role            text        not null,               -- CUSTOMER | ADMIN
    password_hash   text        not null,               -- bcrypt
    password_length integer     not null,               -- length of original password (drives the CWE-20 truncation bug)
    totp_secret     text        not null                -- base32 TOTP seed (Secure2u simulation)
);

-- Module 4 — Encryption at rest (CWE-311 / SR1, SR6)
create table if not exists accounts (
    id              text primary key,
    owner_username  text            not null,
    account_number  text            not null,
    account_name    text            not null,
    balance         numeric(18,2)   not null,
    nric            varchar(512)    not null,            -- sensitive: plaintext or 'enc:v1:...' AES-256 ciphertext
    card_number     varchar(512)    not null,            -- sensitive: plaintext or 'enc:v1:...' AES-256 ciphertext
    secure_stored   boolean         not null default false
);

-- Module 3 — Duplicate transfer protection (CWE-675 / SR5)
create table if not exists transfers (
    id              text primary key,
    created_at      timestamptz     not null,
    from_account    text            not null,
    to_account      text            not null,
    amount          numeric(18,2)   not null,
    idempotency_key text,                                -- intentionally NOT unique (vulnerable path must double-insert)
    status          text            not null,
    secure_mode     boolean         not null
);
create index if not exists idx_transfers_idem on transfers (idempotency_key);

-- Module 2 — Payment authorization (CWE-287 / SR3)
create table if not exists payments (
    id              text primary key,
    created_at      timestamptz     not null,
    merchant        text            not null,
    amount          numeric(18,2)   not null,
    card_last4      text            not null,
    status          text            not null,
    secure_mode     boolean         not null,
    note            varchar(500)
);

-- Shared — append-only, hash-chained audit log (SR5)
create table if not exists audit_log (
    id          bigint generated by default as identity primary key,
    ts          timestamptz     not null,
    actor       text            not null,
    action      text            not null,
    details     varchar(2000),
    prev_hash   text            not null,
    entry_hash  text            not null
);
